parameters:
    project.root_path: '%kernel.project_dir%/../..'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    WirelessLogic\Tests\:
        resource: '%project.root_path%/tests/*'
        exclude: '%project.root_path%/tests/bootstrap.php'

    WirelessLogic\Tests\Behat\Products\ProductsEndToEndContext:
      class: WirelessLogic\Tests\Behat\Products\ProductsEndToEndContext
      arguments:
        $productSource: '%product_source%'
