name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build container
      run: docker-compose up -d

    - name: Install dependencies
      run: docker exec wireless-logic-php composer install

    - name: Run coding standards check
      run: docker exec wireless-logic-php vendor/bin/php-cs-fixer fix --no-interaction --diff -v --dry-run
      
    - name: Run static analysis check
      run: docker exec wireless-logic-php vendor/bin/phpstan analyse -l 9 src/ tests/
      
    - name: Run unit tests
      run: docker exec wireless-logic-php vendor/bin/phpunit
      
    - name: Run feature tests
      run: docker exec wireless-logic-php vendor/bin/behat
