name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make build

    - name: Run coding standards check
      run: docker exec wireless-logic-php vendor/bin/php-cs-fixer fix --no-interaction --diff -v --dry-run
